const fs = require('fs');
const path = require('path');

function compose() {
    const storyboardPath = path.join(__dirname, '../output/storyboard.json');
    if (!fs.existsSync(storyboardPath)) {
        console.error("Error: storyboard.json not found.");
        return;
    }

    const storyboard = JSON.parse(fs.readFileSync(storyboardPath, 'utf8'));
    const slides = storyboard.slides || [];

    const styleStr = `
        * { box-sizing: border-box; }
        html, body { margin: 0; width: 1920px; height: 1080px; overflow: hidden; background: #fffdf6; color: #1b1b1f; font-family: sans-serif; }
        .root { position: relative; width: 1920px; height: 1080px; }
        .scene { position: absolute; inset: 0; background-color: #fffdf6; opacity: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 100px; }
        .anim-obj { font-size: 48px; font-weight: bold; margin: 20px 0; padding: 20px; border-radius: 12px; background: #e2e8f0; text-align: center; width: 100%; opacity: 0; }
        .caption { position: absolute; bottom: 50px; left: 100px; right: 100px; font-size: 40px; font-weight: 900; color: white; -webkit-text-stroke: 2px black; text-align: center; opacity: 0; z-index: 10; }
    `;

    let scenesHTML = '';
    let jsTimelineStr = 'const tl = gsap.timeline();\n';
    let totalDuration = 0;

    slides.forEach((slide, i) => {
        let objectsHTML = '';
        const startTime = totalDuration;

        // Scene entrance
        jsTimelineStr += `tl.set('#scene-${i}', { opacity: 1 }, ${startTime});\n`;
        if (i > 0) jsTimelineStr += `tl.set('#scene-${i-1}', { opacity: 0 }, ${startTime});\n`;

        // TTS Caption animation
        if (slide.tts_script) {
            objectsHTML += `<div class="caption" id="caption-${i}">${slide.tts_script}</div>\n`;
            jsTimelineStr += `tl.to('#caption-${i}', { opacity: 1, duration: 0.5 }, ${startTime + 0.1});\n`;
        }

        // Object animations based on AI storyboard timings
        (slide.animations || []).forEach((anim, j) => {
            objectsHTML += `<div class="anim-obj" id="obj-${i}-${j}">${anim.target}</div>\n`;
            const absTime = startTime + anim.start_time;
            jsTimelineStr += `tl.fromTo('#obj-${i}-${j}', { opacity: 0, y: 50, scale: 0.8 }, { opacity: 1, y: 0, scale: 1, duration: 0.8, ease: "back.out(1.5)" }, ${absTime});\n`;
        });

        scenesHTML += `<div id="scene-${i}" class="scene">\n${objectsHTML}</div>\n`;
        totalDuration += slide.duration;
    });

    const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
  <style>${styleStr}</style>
</head>
<body>
  <div id="root" class="root" data-composition-id="main" data-start="0" data-duration="${totalDuration}" data-width="1920" data-height="1080">
    ${scenesHTML}
  </div>
  <script>${jsTimelineStr}</script>
</body>
</html>`;

    fs.writeFileSync(path.join(__dirname, '../output/index.html'), html);
    console.log("Composed index.html with GSAP timeline generated by AI Director.");
    
    // Create package.json for hyperframes
    const pkg = {
      name: "method-10-director",
      private: true,
      scripts: { "render": "npx --yes hyperframes@latest render" }
    };
    fs.writeFileSync(path.join(__dirname, '../output/package.json'), JSON.stringify(pkg, null, 2));
}

compose();
